//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09.09.2014 11:43:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace NorthwindDevart
{

    /// <summary>
    /// There are no comments for NorthwindDevart.Customer, NorthwindDevart in the schema.
    /// </summary>
    public partial class Customer {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Customer constructor in the schema.
        /// </summary>
        public Customer()
        {
            this.CustomerDemographics = new HashSet<CustomerDemographic>();
            this.Orders = new HashSet<Order>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for CustomerID in the schema.
        /// </summary>
        public virtual string CustomerID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CompanyName in the schema.
        /// </summary>
        public virtual string CompanyName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ContactName in the schema.
        /// </summary>
        public virtual string ContactName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ContactTitle in the schema.
        /// </summary>
        public virtual string ContactTitle
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Address in the schema.
        /// </summary>
        public virtual string Address
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for City in the schema.
        /// </summary>
        public virtual string City
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Region in the schema.
        /// </summary>
        public virtual string Region
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for PostalCode in the schema.
        /// </summary>
        public virtual string PostalCode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Country in the schema.
        /// </summary>
        public virtual string Country
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Phone in the schema.
        /// </summary>
        public virtual string Phone
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Fax in the schema.
        /// </summary>
        public virtual string Fax
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CustomerDemographics in the schema.
        /// </summary>
        public virtual ISet<CustomerDemographic> CustomerDemographics
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        public virtual ISet<Order> Orders
        {
            get;
            set;
        }
    }

}
