//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09.09.2014 11:43:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace NorthwindDevart
{

    /// <summary>
    /// There are no comments for NorthwindDevart.CustomerDemographic, NorthwindDevart in the schema.
    /// </summary>
    public partial class CustomerDemographic {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for CustomerDemographic constructor in the schema.
        /// </summary>
        public CustomerDemographic()
        {
            this.Customers = new HashSet<Customer>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for CustomerTypeID in the schema.
        /// </summary>
        public virtual string CustomerTypeID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CustomerDesc in the schema.
        /// </summary>
        public virtual string CustomerDesc
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        public virtual ISet<Customer> Customers
        {
            get;
            set;
        }
    }

}
