//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09.09.2014 11:43:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace NorthwindDevart
{

    /// <summary>
    /// There are no comments for NorthwindDevart.Order, NorthwindDevart in the schema.
    /// </summary>
    public partial class Order {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Order constructor in the schema.
        /// </summary>
        public Order()
        {
            this.Freight = 0m;
            this.OrderDetails = new HashSet<OrderDetail>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for OrderID in the schema.
        /// </summary>
        public virtual int OrderID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OrderDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> OrderDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for RequiredDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> RequiredDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShippedDate in the schema.
        /// </summary>
        public virtual System.Nullable<System.DateTime> ShippedDate
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShipVia in the schema.
        /// </summary>
        public virtual System.Nullable<int> ShipVia
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Freight in the schema.
        /// </summary>
        public virtual System.Nullable<decimal> Freight
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShipName in the schema.
        /// </summary>
        public virtual string ShipName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShipAddress in the schema.
        /// </summary>
        public virtual string ShipAddress
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShipCity in the schema.
        /// </summary>
        public virtual string ShipCity
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShipRegion in the schema.
        /// </summary>
        public virtual string ShipRegion
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShipPostalCode in the schema.
        /// </summary>
        public virtual string ShipPostalCode
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for ShipCountry in the schema.
        /// </summary>
        public virtual string ShipCountry
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        public virtual Customer Customer
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Employee in the schema.
        /// </summary>
        public virtual Employee Employee
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        public virtual ISet<OrderDetail> OrderDetails
        {
            get;
            set;
        }
    }

}
