//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 09.09.2014 11:43:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace NorthwindDevart
{

    /// <summary>
    /// There are no comments for NorthwindDevart.Category, NorthwindDevart in the schema.
    /// </summary>
    public partial class Category {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();
        
        #endregion
        /// <summary>
        /// There are no comments for Category constructor in the schema.
        /// </summary>
        public Category()
        {
            this.Products = new HashSet<Product>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for CategoryID in the schema.
        /// </summary>
        public virtual int CategoryID
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for CategoryName in the schema.
        /// </summary>
        public virtual string CategoryName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        public virtual string Description
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Picture in the schema.
        /// </summary>
        public virtual byte[] Picture
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        public virtual ISet<Product> Products
        {
            get;
            set;
        }
    }

}
