//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Messages;

namespace BerskaClient.BerskaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BerskaService.IStoreService")]
    public interface IStoreService {
        
        // CODEGEN: Generating message contract since the wrapper name (SaveRequest) of message SaveRequest does not match the default value (SaveStore)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/SaveStore", ReplyAction="http://tempuri.org/IStoreService/SaveStoreResponse")]
        SaveResponse SaveStore(SaveRequest request);
    }
    
  
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreServiceChannel : BerskaClient.BerskaService.IStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreServiceClient : System.ServiceModel.ClientBase<BerskaClient.BerskaService.IStoreService>, BerskaClient.BerskaService.IStoreService {
        
        public StoreServiceClient() {
        }
        
        public StoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaveResponse BerskaClient.BerskaService.IStoreService.SaveStore(SaveRequest request) {
            return base.Channel.SaveStore(request);
        }
        
        public bool SaveStore(Entities.BaseEntity store) {
            SaveRequest inValue = new SaveRequest();
            inValue.store = store;
            SaveResponse retVal = ((BerskaClient.BerskaService.IStoreService)(this)).SaveStore(inValue);
            return retVal.Result;
        }
    }
}
