//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindClientApp.ProductServiceConsumer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SurrogateProduct", Namespace="http://schemas.datacontract.org/2004/07/SurrogeteLibrary")]
    [System.SerializableAttribute()]
    public partial class SurrogateProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.northwind.com/services/productservices", ConfigurationName="ProductServiceConsumer.NorthwindProductService")]
    public interface NorthwindProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.northwind.com/services/productservices/NorthwindProductService/GetProd" +
            "ucts", ReplyAction="http://www.northwind.com/services/productservices/NorthwindProductService/GetProd" +
            "uctsResponse")]
        NorthwindClientApp.ProductServiceConsumer.SurrogateProduct[] GetProducts(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.northwind.com/services/productservices/NorthwindProductService/GetProd" +
            "uctByName", ReplyAction="http://www.northwind.com/services/productservices/NorthwindProductService/GetProd" +
            "uctByNameResponse")]
        NorthwindClientApp.ProductServiceConsumer.SurrogateProduct[] GetProductByName(string firstLetter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NorthwindProductServiceChannel : NorthwindClientApp.ProductServiceConsumer.NorthwindProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NorthwindProductServiceClient : System.ServiceModel.ClientBase<NorthwindClientApp.ProductServiceConsumer.NorthwindProductService>, NorthwindClientApp.ProductServiceConsumer.NorthwindProductService {
        
        public NorthwindProductServiceClient() {
        }
        
        public NorthwindProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NorthwindProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NorthwindProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NorthwindProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public NorthwindClientApp.ProductServiceConsumer.SurrogateProduct[] GetProducts(int categoryId) {
            return base.Channel.GetProducts(categoryId);
        }
        
        public NorthwindClientApp.ProductServiceConsumer.SurrogateProduct[] GetProductByName(string firstLetter) {
            return base.Channel.GetProductByName(firstLetter);
        }
    }
}
